branches: 
  notifications: 
    slack: "stlab:P23OMUJ8T4Pa05OON0VDYwIf"
  only:
  - master
  - develop
matrix: 
  include: 
  - language: c++
    os: osx
    osx_image: xcode8.3
    script: CC=clang++ ./build.sh
  - language: ruby
    rvm: ruby-head
    install: gem install jekyll html-proofer github-pages
    script: bundle exec jekyll build && htmlproofer --http-status-ignore 0 ./_site
    env: 
      global: 
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    sudo: false
