# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: stlab
#subtitle not currently used
subtitle: The continuing saga.
email: sean.parent@stlab.cc
description: > # this means to ignore newlines until "baseurl:"
    stlab hosts modern, modular c++ algorithms and data structures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stlab.cc" # the base hostname & protocol for your site
twitter_username: SeanParent
github_username:  sean-parent

exclude:
    - vendor # For Travis-CI (see https://jekyllrb.com/docs/continuous-integration/)
    - _source
    - stlab.bbprojectd/

# Build settings
markdown: kramdown

#wire this up
comments :
  provider : disqus
  disqus :
    short_name : stlab-cc
