# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: STLab
#subtitle not currently used
subtitle: The continuing saga.
email: sean.parent@stlab.cc
description: > # this means to ignore newlines until "baseurl:"
  STLab hosts modern, modular c++ algorithms and data structures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stlab.cc" # the base hostname & protocol for your site
twitter_username: SeanParent
github_username:  sean-parent

# For Travis-CI (see https://jekyllrb.com/docs/continuous-integration/)
exclude: [vendor]

# Build settings
markdown: kramdown

# Disqus Comments
disqus_short_name: stlab-cc
disqus_show_comment_count: false
